# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# url: http://anielaolsztynek.pl
url: "" # the base hostname & protocol for your site, e.g. http://example.com
name: Parafia pod wezwaniem Błogosławionej Anieli Salawy w Olsztynku
title: Parafia pod wezwaniem Błogosławionej Anieli Salawy w Olsztynku
description: >
  Rzymskokatolicka Parafia pod wezwaniem
  Błogosławionej Anieli Salawy w
  Olsztynku
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
lang: pl

urls:
  kronika_base: https://anielaolsztynek-kronika.web.app
  wp_content_base: /assets/wp-content
wp_content_base: /assets/wp-content

menu:
  - title: Strona główna
    url: /
  - title: Porządek nabożeństw
    url: /porzadek-nabozenstw/
  - title: Caritas – 1%
    url: /caritas-1/
  - title: Galeria zdjęć
    url: /galeria/
  - title: Kroniki parafialne
    url: /kroniki-parafialne/
  - title: Róże Różańcowe
    url: /roze-rozancowe/
  - title: Ministranci
    url: /ministranci/
  - title: Sakramenty
    url: /sakramenty/
  - title: Schola
    url: /schola/
  - title: Kontakt
    url: /kontakt/
  - title: Historia parafii
    url: /historia-parafii/
  - title: O patronce
    url: /o-patronce/

jekyll-archives:
  enabled:
    - year
    - month
  layout: home
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

paginate: 10

# Build settings
markdown: CommonMark
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-commonmark

exclude:
  - .jekyll-cache
