name: Build-n-deploy
on:
  push:
    branches:
      - master

env:
  BUILDER_IMAGE: ghcr.io/anielaolsztynek/anielaolsztynek.pl-2020:sha-3edf116

jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker pull ${BUILDER_IMAGE}
      - name: Build
        run: |
          docker run \
            -v .:/app \
            $BUILDER_IMAGE \
            bash -c "cd public/anielaolsztynek.pl && bundle exec jekyll build"
      - run: ls -la public/anielaolsztynek.pl/_site

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@v2.0.0
      #   with:
      #     args: deploy --only hosting
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
